S3_SR = 16_000
S3_HOP = 160
S3_TOKEN_HOP = 640
S3_TOKEN_RATE = 25

SPEECH_VOCAB_SIZE = 6561
SPEECH_TOKENIZER_MODEL = "speech_tokenizer_v2_25hz"

SOT = "[START]"
EOT = "[STOP]"
UNK = "[UNK]"
SPACE = "[SPACE]"

SPECIAL_TOKENS = [
    SOT, EOT, UNK, SPACE,
    "[PAD]", "[SEP]", "[CLS]", "[MASK]",
]

SOS = SPEECH_VOCAB_SIZE
EOS = SPEECH_VOCAB_SIZE + 1
